### ISSUE TITLE
Request: Make the PIA apk available in f-droid.org

### ISSUE THREAD

**Issue by sifr01** [pia-foss/mobile-android-legacy#16] opened 2021-11-04 15:45 UTC
Seeing as this app is FOSS, it would be great if it was available on the f-droid.org app/repository. Iv seen that other (not as good ;-) VPN service providers have their apps on f-droid.

**Comment by ueshiba** [comment] 2021-11-04 15:52
Hello @sifr01 

You can download the APK directly from our website https://www.privateinternetaccess.com/download/android-vpn-app (at the bottom of the page) or here: https://installers.privateinternetaccess.com/download/pia-android-3.12.2-10569.apk

But def we will consider your proposal! 

Regards

**Comment by bingoxo** [comment] 2022-01-28 11:17
any update on this ?

**Comment by sifr01** [comment] 2022-05-06 18:57
The [PIA changelog](https://www.privateinternetaccess.com/pages/changelog) doesnt provide checksums for PIA's android app releases. Whereas if the android app was made available in Fdroid, PGP signatures of the apk would be made available as a form of verification to mitigate against MiTM attacks.

**Comment by kp-juan-docal** [comment] 2023-08-29 12:34
Closing it as a duplicate of the previous one https://github.com/pia-foss/android/issues/4

**Closed as completed by kp-juan-docal** 2023-08-29 12:34 UTC
